title = "CloudEvents"
baseURL = "/"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
font_awesome_version = "5.11.2"

[params.logos]
navbar = "cloudevents-icon-color.png"
hero = "cloudevents-icon-color.png"
footer = "cloudevents-icon-color.png"

[[params.fonts]]
name = "Montserrat"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.sdks]]
name = "Go"
tag = "go"

[[params.sdks]]
name = "JavaScript"
tag = "javascript"

[[params.sdks]]
name = "Java"
tag = "java"

[[params.sdks]]
name = "C#"
tag = "csharp"

[[params.sdks]]
name = "Ruby"
tag = "ruby"

[[params.sdks]]
name = "PHP"
tag = "php"

[[params.sdks]]
name = "Python"
tag = "python"

[[params.sdks]]
name = "Rust"
tag = "rust"

[[params.sdks]]
name = "PowerShell"
tag = "powershell"

[[params.social]]
tag = "github"
name = "GitHub"
url = "https://github.com/cloudevents"
color = "black"

[[params.social]]
tag = "twitter"
name = "Twitter"
url = "https://twitter.com/CloudEventsIO"
color = "twitter-blue"

# Multilingual
[languages]
[languages.en]
weight = 1
languageCode = "en"
languageName = "English"

[[languages.en.menus.main]]
name = "Specification"
url = "https://github.com/cloudevents/spec"
weight = 1

[[languages.en.menus.main]]
name = "Primer"
url = "https://github.com/cloudevents/spec/blob/main/cloudevents/primer.md"
weight = 2

[[languages.en.menus.main]]
identifier = "project"
name = "Project"
weight = 3

[[languages.en.menus.main]]
name = "Code of conduct"
url = "https://github.com/cncf/foundation/blob/main/code-of-conduct.md"
parent = "project"
weight = 1

[[languages.en.menus.main]]
name = "Governance"
url = "https://github.com/cloudevents/spec/blob/main/docs/GOVERNANCE.md"
parent = "project"
weight = 2

[[languages.en.menus.main]]
name = "Contributors"
url = "https://github.com/cloudevents/spec/blob/main/docs/contributors.md"
parent = "project"
weight = 3

[languages.zh-cn]
weight = 2
languageCode = "zh-CN"
languageName = "简体中文"
hasCJKLanguage = true

[[languages.zh-cn.menus.main]]
name = "规范"
url = "https://github.com/cloudevents/spec"
weight = 1
[[languages.zh-cn.menus.main]]
name = "入门文档"
url = "https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/primer.md"
weight = 2
[[languages.zh-cn.menus.main]]
identifier = "project"
name = "项目"
weight = 3
[[languages.zh-cn.menus.main]]
name = "行为准则"
url = "https://github.com/cncf/foundation/blob/main/code-of-conduct-languages/zh.md"
parent = "project"
weight = 1

[[languages.zh-cn.menus.main]]
name = "管理"
url = "https://github.com/cloudevents/spec/blob/main/docs/languages/zh-CN/GOVERNANCE.md"
parent = "project"
weight = 2

[[languages.zh-cn.menus.main]]
name = "贡献者"
url = "https://github.com/cloudevents/spec/blob/main/docs/languages/zh-CN/contributors.md"
parent = "project"
weight = 3
